pipeline:
  build-and-push:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    settings:
      repo: redpencil/virtuoso
      tags: "feature-${CI_COMMIT_SOURCE_BRANCH##feature/}"
    when:
      event:
        - push
branches:
  - feature/*
