pipeline:
  build-and-push:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    settings:
      repo: redpencil/virtuoso
      tags: ${CI_COMMIT_BRANCH/\//-}
    when:
      event:
        - push
branches: '*\\/*'
