pipeline:
  build-and-push:
    image: plugins/docker
    settings:
      repo: redpencil/virtuoso
      tags: latest
      secrets: [docker_username, docker_password]
    when:
      event:
        - push
branches:
  - master
