pipeline:
  build-and-push:
    image: plugins/docker
    settings:
      repo: redpencil/virtuoso
      secrets: [docker_username, docker_password]
      tags: ${CI_REPO_TAG##v} # strips v from the tag
    when:
      event: tag
      tag: v*
branches:
  - master
