pipeline:
  build-and-release:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    settings:
      repo: redpencil/virtuoso
      tags: ${CI_COMMIT_TAG##v} # strips v from the tag
when:
  event: tag
  tag: v*
